# Generated by Django 3.2.7 on 2024-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240317_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='cart/cart-detail/bakery/pimg'),
        ),
    ]
