# Generated by Django 3.2.7 on 2024-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_orderitem_ordernew'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
