# Generated by Django 3.2.7 on 2024-03-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernew',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ordernew',
            name='lastname',
        ),
    ]
