# Generated by Django 3.2.7 on 2024-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20240324_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='paymentmode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
